package br.com.rickgurgel.Player.enums;

public enum GoalkeeperAttributes {
    GOALS_CONCEDED_PER_GAME,
    PENALTIES_SAVED,
    SAVES_PER_GAME,
    SUCCESSFUL_RUNS_OUT_PER_GAME,
    GOALS_CONCEDED,
    CONCEDED_FROM_INSIDE_BOX,
    CONCEDED_FROM_OUTSIDE_BOX,
    SAVES_MADE,
    GOALS_PREVENTED,
    SAVES_FROM_INSIDE_BOX,
    SAVES_FROM_OUTSIDE_BOX,
    SAVES_CAUGHT,
    SAVES_PARIED
}
